### ISSUE TITLE
ESRI Topographic [BUG]

### ISSUE THREAD

**Issue by L-Maximillian** [hawgops/hawgops-public#7]
**What service are you writing the bug about? (Delete services not applicable)**
HawgOps | CAS

**Describe the bug**
Every time i choose ESRI Topographic view it updates the site, but goes white, with no option but refreshing the site. And when i refresh the site it goes back to Google Hybrid as a default.

**To Reproduce**
1. Go to '[...](https://hawg-ops.com/)'
2. Click on 'ESRI Topographic'

**Expected behavior**
I want to get ESRI Topographic view when i select it.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]
 - Version [Dont know]

**Additional context**

**Comment by chris-m92** [comment]
This was my fault - I made an update yesterday and a file wasn't appropriately included. The issue is resolved and selecting any of the ESRI basemaps will no longer crash the site.

**Comment by chris-m92** [comment]
Reopening - 
Further testing on live site shows that ESRI basemaps are functional, however, airspace and other basemaps are not. Investigating.

**Comment by L-Maximillian** [comment]
Hi Chris,
Do you have a time estimate for when ESRI functions will be functional agian?

**Comment by L-Maximillian** [comment]
Hi Chris
Do you have a time estimate for when ESRI will be functional agian?

**Comment by chris-m92** [comment]
Good morning

Back to fully functional
I can go into the details if you like, but end state is we're back up.

Sorry for the inconvenience.

**Comment by L-Maximillian** [comment]
Is all good from this end, thanks a lot!
